### ISSUE TITLE
Expect100Continue does not get called

### ISSUE THREAD

**Issue by CumpsD** [influxdb/influxdb-fsharp#8]
It seems this line does not get called when I use this library: https://github.com/influxdb/influxdb-fsharp/blob/master/src/InfluxDB.FSharp/Http.fs#L7

```
do if ServicePointManager.Expect100Continue then ServicePointManager.Expect100Continue <- false
```

This caused it to only send 2 requests and then stop, because of webrequests hanging internally.

I traced it back in your old commits when you replaced Http.fs with the custom implementation. They made an explicit call to disable it, while now it is this `do` line.

Do I need to do anything special to get F# to execute that line? When I manually disable `Expect100Continue` on start of my own program all is fine.

**Comment by xkrt** [comment]
Very interesting!
I think there tricky problem with with static initialization optimization, see http://stackoverflow.com/questions/18619093/how-to-execute-module-do-block

Anyway, I try to resolve this following fix https://github.com/influxdb/influxdb-fsharp/commit/7383eebe8e6adb20b84cf1afa7e35d69040349ba
Can you try it?
